// Converts the head trace (drawn in pixel coordinates over the reference
// headshot, 1656×1884) into the Peep rig's 400×440 viewBox.
// Usage: node scripts/peep/convert-trace.mjs > src/components/illustrations/peep/head-paths.ts
import { readFileSync } from "node:fs";

const SCALE = 0.1342; // headshot px → rig units
const [PHOTO_CX, PHOTO_TOP] = [805, 150]; // face centre x, hair top y in the photo
const [RIG_CX, RIG_TOP] = [200, 52];

const convert = (d) => {
  let i = 0;
  return d.replace(/-?\d+(?:\.\d+)?/g, (n) => {
    const v = Number(n);
    const out = i++ % 2 === 0 ? (v - PHOTO_CX) * SCALE + RIG_CX : (v - PHOTO_TOP) * SCALE + RIG_TOP;
    return String(Math.round(out * 10) / 10);
  });
};

const rows = readFileSync(new URL("./head-trace.tsv", import.meta.url), "utf8")
  .trim()
  .split("\n")
  .map((line) => line.split("\t"));

console.log(`// Generated by scripts/peep/convert-trace.mjs from head-trace.tsv — do not edit by hand.
// Traced over Toluwalope's headshot, then scaled into the 400×440 rig viewBox.
export const head = {
${rows.map(([k, d]) => `  ${k}: "${convert(d)}",`).join("\n")}
} as const;
`);
